# Generated by Django 5.2.6 on 2026-01-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commun', models.CharField(max_length=100)),
                ('nom_savant', models.CharField(max_length=100)),
                ('embranchement', models.CharField(max_length=50)),
                ('classe', models.CharField(max_length=50)),
                ('ordre', models.CharField(max_length=50)),
                ('sous_ordre', models.CharField(blank=True, max_length=50, null=True)),
                ('famille', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('statut_iucn', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
