# Generated by Django 4.2.11 on 2026-01-07 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commun', models.CharField(max_length=100)),
                ('nom_savant', models.CharField(max_length=200)),
                ('embranchement', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=100)),
                ('ordre', models.CharField(max_length=100)),
                ('sous_ordre', models.CharField(max_length=100)),
                ('famille', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('statut_iucn', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observo.animal')),
            ],
        ),
    ]
