# Generated by Django 5.2.6 on 2026-01-09 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='observation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL),
        ),
    ]
